platform :osx, '10.14'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'ephemeral', 'Flutter-Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure \"flutter pub get\" is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Flutter-Generated.xcconfig, then run \"flutter pub get\""
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_macos_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_macos_pods File.dirname(File.realpath(__FILE__))

  script_phase(
      name: 'Copy Native Libraries',
      execution_position: :before_compile,
      script: <<-'SCRIPT'
        # Flutter-Projekt-Root ermitteln
        FLUTTER_ROOT=$(cat "${SRCROOT}/Flutter/ephemeral/Flutter-Generated.xcconfig" | grep 'FLUTTER_ROOT=' | cut -d'=' -f2)

        # Pfade konstruieren
        PLUGIN_DIR="${SRCROOT}/../../flutter_lmdb2"
        SOURCE_DIR="${PLUGIN_DIR}/lib/native/macos"
        TARGET_DIR="${PLUGIN_DIR}/macos/Frameworks"

        echo "Plugin directory: ${PLUGIN_DIR}"
        echo "Source directory: ${SOURCE_DIR}"
        echo "Target directory: ${TARGET_DIR}"

        mkdir -p "${TARGET_DIR}"

        if [ -d "${SOURCE_DIR}" ]; then
          echo "Copying native libraries..."
          cp -R "${SOURCE_DIR}"/* "${TARGET_DIR}/"
        else
          echo "Warning: Source directory not found"
          exit 1
        fi
  SCRIPT
  )

  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_macos_build_settings(target)
  end
end
