name: dart_lmdb2
description: A modern Dart wrapper for LMDB (Lightning Memory-Mapped Database), providing both high-level convenience methods and low-level transaction control.
version: 0.9.8
homepage: https://github.com/grammatek/dart_lmdb2

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  args: ^2.6.0
  ffi: ^2.1.0
  path: ^1.8.3
  http: ^1.2.0
  yaml: ^3.1.2
  archive: ^3.4.9
  crypto: ^3.0.3

dev_dependencies:
  analyzer: ^6.11.0
  ffigen: ^16.0.0
  build_runner: ^2.4.14
  lints: ^5.0.0
  test: ^1.17.0
  pana:

ffigen:
  output: 'lib/src/generated_bindings.dart'
  headers:
    entry-points:
      - 'src/include/lmdb.h'
  include-unused-typedefs: true
  preamble: |
    // ignore_for_file: type=lint, unused_element, unused_field, unused_typedef

executables:
  build: build
  fetch_native: fetch_native

scripts:
  build: build

example:
  include: ["example/**"]

platforms:
  android:
  ios:
  linux:
  macos:
  windows:
