name: Dart LMDB2

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_test_dart_lmbd2:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            cmake-install: sudo apt-get install -y cmake build-essential
          - os: macos-latest
            cmake-install: brew install cmake
          - os: windows-latest
            cmake-install: choco install cmake
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./dart_lmdb2
    steps:
      - uses: actions/checkout@v4

      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Install CMake and build tools
        run: ${{ matrix.cmake-install }}

      - name: Install dependencies
        run: |
          dart pub get

      - name: Build native library
        run: dart run tool/build.dart

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: dart analyze --fatal-infos

      - name: Run tests
        run: dart test -j 1

      # Upload built libraries as artifacts
      - name: Upload native library
        uses: actions/upload-artifact@v3
        with:
          name: native-lib-${{ matrix.os }}
          path: lib/src/native/*

  build_test_flutter_lmbd2:
    strategy:
      matrix:
        os: [macos-latest]
        flutter: ['3.27.1']
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./flutter_lmdb2
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.flutter }}
          channel: 'stable'
      - uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            ~/.gradle
            ~/Library/Caches/CocoaPods
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-flutter-
      - name: Install dependencies
        run: |
          flutter config --no-analytics --no-cli-animations
          flutter pub get
      - name: iOS Setup
        if: matrix.os == 'macos-latest'
        run: |
          flutter config --enable-ios
          flutter precache --ios  # Cache iOS dependencies

      - name: Build and Validate iOS Plugin
        if: matrix.os == 'macos-latest'
        run: |
          dart run tool/build.dart --ios
          cd ios || exit 1
          pod repo update
          pod lib lint \
            --allow-warnings \
            --verbose \
            --platforms=ios \
            --skip-tests \
            --no-clean

  publish_dart_lmbd2:
    needs: build_test_dart_lmbd2
    if: github.event_name == 'release' && github.event.action == 'created'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Download all native libraries
        uses: actions/download-artifact@v3
        with:
          path: lib/src/native/

      # Optional: Publish to pub.dev
      - name: Publish to pub.dev
        run: dart pub publish --force
        env:
          PUB_CREDENTIALS: ${{ secrets.PUB_CREDENTIALS }}

  docs_dart_lmbd2:
    needs: build_test_dart_lmbd2
    runs-on: ubuntu-latest
    defaults:
          run:
            working-directory: ./dart_lmdb2
    steps:
      - uses: actions/checkout@v4

      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Install dependencies
        run: |
          dart pub get

      - name: Generate documentation
        run: dart doc
